parameters:
  platform: Linux
  vmImage: ubuntu-16.04
  STAGING_DIRECTORY: /home/vsts/STAGING
  STAGING_DIRECTORY_UNIX: /home/vsts/STAGING
  ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
  ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    variables:
      STAGING_DIRECTORY: ${{ parameters.STAGING_DIRECTORY }}
      STAGING_DIRECTORY_UNIX: ${{ parameters.STAGING_DIRECTORY_UNIX }}
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      ESY__CACHE_SOURCE_TARBALL_PATH: ${{ parameters.ESY__CACHE_SOURCE_TARBALL_PATH }}

    steps:
      - template: utils/use-node.yml
      - template: utils/use-esy.yml
      - template: utils/restore-build-cache.yml
      - script: "esy i"
        displayName: "esy i"
      - script: "esy b"
        displayName: "esy b"
      - script: "esy b dune runtest"
        displayName: 'Running dune runtest alias'
      - script: esy npm-release
        displayName: 'Creating npm release'
      - script: npm pack
        displayName: 'NPM packing...'
        workingDirectory: '_release'
      - script: 'sudo npm install -g ./pesy-0.5.0-alpha.2.tgz --unsafe-perm=true'
        displayName: 'npm link... for tests'
        workingDirectory: '_release'
      - template: utils/publish-build-cache.yml
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: ${{ parameters.platform }}"
        inputs:
          PathtoPublish: "_release"
          ArtifactName: ${{ parameters.platform }}
